version: 2
updates:
  - package-ecosystem: pip
    directory: "/functions/python-function/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
